name: Setup python
description: Setup python repository

inputs:
  python-version:
    description: "Python version"
    default: "3.10"
  fetch-depth:
    description: "Depth for git fetch"
  sdir:
    description: "Source directory"
    default: ""
    
runs:
  using: "composite"
  steps:
    - name: Checkout repository with fetch-depth
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{inputs.fetch-depth}}
        sparse-checkout: ${{inputs.sdir}}
        # files in the project root are not included during checkout
        sparse-checkout-cone-mode: false

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Move all files to root
      if: ${{inputs.sdir}} != ""
      shell: bash
      run: |
        rsync -a ${{inputs.sdir}}/ .

    - name : Upgrade pip
      shell : bash
      run: |
        python -m pip install --upgrade pip

    - name: Install poetry
      shell: bash
      run: pipx install poetry==1.2.0

    - name: Install package
      shell: bash
      run: |
        poetry lock
        poetry install --with dev