name: Setup python
description: Setup python repository

inputs:
  python-version:
    description: "Python version"
    default: "3.10"
  fetch-depth:
    description: "Depth for git fetch"
  sdir:
    description: "Source directory"
    default: "."
    
runs:
  using: "composite"
  steps:
    - name: Checkout repository with fetch-depth
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{inputs.fetch-depth}}

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Change directory
      shell: bash
      if: ${{ inputs.sdir != '.' }}
      run: cd ${{ inputs.sdir }}

    - name: List files
      shell: bash
      run: |
        echo $(ls)

    - name : Upgrade pip
      shell : bash
      run: |
        python -m pip install --upgrade pip

    - name: Install dependencies
      shell: bash
      run: |
        pip install flake8 flake8-rst-docstrings

    - name: Install package
      shell: bash
      run: |
        pip install .