name: Docsumentation merge check
description: Checks if merge breaks documentation

runs:
  using: 'composite'
  steps:
    - name: Merge HEAD into main and gh-pages
      shell: bash
      run: |
        git config pull.rebase false
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git branch temp
        git checkout temp
        echo "created temporary branch"

        git pull origin ${{ github.head_ref }}
        echo "Pulled ${{ github.head_ref }} into temporary branch"
        git checkout "${{ github.head_ref }}"

        git checkout temp
        git merge ${{ github.head_ref }}
        echo "merged ${{ github.head_ref }} into temporary branch"

        git pull origin gh-pages
        git checkout gh-pages
        git merge temp
        echo "merged temporary branch into gh-pages"

    - name: Build docs
      uses: giocaizzi/python-dev-actions/.github/actions/documentation@main
