name: Lint with Flake8
description: 'Lint Python code with Flake8'

inputs:
  backend:
    description: "Backend to use (poetry, setuptools)"
    default: "poetry"

runs:
  using: composite
  steps:
    - shell : bash
      run: |
        echo "Backend: ${{ inputs.backend }}"

    - name: Lint with flake8 with setuptools backend
      if: inputs.backend == 'setuptools'
      shell: bash
      run: flake8 ${{ github.event.repository.name }}

    - name: Lint with flake8 with poetry backend
      if: inputs.backend == 'poetry'
      shell: bash
      run: poetry run flake8 ${{ github.event.repository.name }}
    

