name: Commit to GitHub
description: 'Commits changes to the repository'

inputs:
  what:
    description: 'What to commit'
    default: '.'
  message:
    description: 'Commit message'
    required: true

runs:
    using: "composite"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # The last command will fail if no changes were present, so we ignore
      # the return code.
      - name: Commit documentation changes
        shell: bash
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Actions: Sync mobile config" -a  || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}