name: Commit to GitHub
description: 'Commits changes to the repository and push to Github'



inputs:
  what:
    description: 'What to commit'
    default: '.'
  message:
    description: 'Commit message'
    required: true
  github-token:
    description: 'GitHub token'
    required: true
  branch:
    description: 'Branch to push to.'

runs:
    using: "composite"
    steps:
      - name : Print current branch
        shell: bash
        run : |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch is $BRANCH"

      - name: Set up Git
        shell: bash
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"

      - name: Print git status
        shell: bash
        run: |
          git status

      - name: Add changes
        shell: bash
        run: |
          git add ${{ inputs.what }}

      # The command will fail if no changes were present, so we ignore
      # the return code.
      - name: Commit documentation changes
        shell: bash
        run: |
          git commit -m "${{ inputs.message }}" -a  || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ inputs.github-token }}
          branch: ${{ inputs.branch }}