name: Build with poetry
description: Build and install python package with poetry

runs:
  using: "composite"
  steps:
    - name: Install poetry
      shell: bash
      run: pipx install poetry==1.7.1

    - name: Install package
      shell: bash
      run: |
        poetry install --with dev