name: Deployment

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      os:
        description: "Operating system to run on"
        default: 'ubuntu-latest'
        type: string
      python-version:
        description: "Python version to run on"
        default: '3.9'
        type: string

jobs:
  # Run pre-checks workflow.
  # - lint
  # - versioning (if PR)
  # - documentation-merge-check (if PR)
  pre-checks:
    name:  ${{ inputs.os }}-py${{ inputs.python-version }}
    uses: giocaizzi/python-dev-actions/.github/workflows/pre-checks.yml@main
    with :
      os: ${{ inputs.os }}
      python-version: ${{ inputs.python-version }}


  # Run Tests workflow on specified OS for a matrix of python versions
  tests:
    name: ${{ inputs.os }} tests
    needs: "pre-checks"
    uses: giocaizzi/python-dev-actions/.github/workflows/tests.yml@main
    with:
      os: ${{ inputs.os }}

  # # Execute post-deployment actions
  # post-deployment:
  #   name: Open issues from TODOs
  #   needs: "tests"
  #   uses: giocaizzi/python-dev-actions/.github/actions/todo@main


