name: Deployment

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      os:
        description: "Operating system to run on"
        default: 'ubuntu-latest'
        type: string

jobs:
  # Run pre-checks workflow.
  # Default: ubuntu-latest and python 3.9
  # - lint
  # - versioning
  # - documentation-merge-check
  pre-checks:
    name: Run prechecks
    uses: giocaizzi/python-dev-actions/.github/workflows/pre-checks.yml@main


  # Run Tests workflow on specified OS for a matrix of python versions
  tests:
    name: Tests with Pytest
    needs: "pre-checks"
    uses: giocaizzi/python-dev-actions/.github/workflows/tests.yml@main
    with:
      os: ${{ inputs.os }}

  # # Execute post-deployment actions
  # post-deployment:
  #   name: Open issues from TODOs
  #   needs: "tests"
  #   uses: giocaizzi/python-dev-actions/.github/actions/todo@main


