name: Deployment

on:
  workflow_call:
    inputs:
      os:
        description: "Operating system to run on"
        default: 'ubuntu-latest'
        type: string

jobs:
  # First check for linting errors and versioning issues
  pre-checks:
    name: Run prechecks
    uses: giocaizzi/python-dev-actions/.github/workflows/pre-checks.yml@main

  # Run Tests
  tests:
    name: Tests with Pytest
    uses: giocaizzi/python-dev-actions/.github/workflows/tests.yml@main
    with:
      os: ${{ inputs.os }}
    needs: "pre-checks"

  # If in a pull request and in 'ubuntu-latest', run documentation prechecks
  documentation-prechecks:
    name: Documentation prechecks
    if: github.event_name == 'pull_request' && inputs.os == 'ubuntu-latest'
    uses: giocaizzi/python-dev-actions/.github/workflows/documentation_precheck.yml@main
    needs: "pre-checks"
