name: Documentation build

on:
  workflow_call:

jobs:
  docs:
    name: Building documentation with Python 3.9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - uses: actions/checkout@v4

      - name: Build docs
        uses: giocaizzi/python-dev-actions/.github/actions/documentation@main

      - name: Commit built documentation
        uses: giocaizzi/python-dev-actions/.github/actions/commit@main
        with:
          message: "Actions: Documentation build"
          github-token: ${{ secrets.GITHUB_TOKEN }}