name: Pre-checks

on:
  workflow_call:

jobs:
  # First check for linting errors and versioning issues
  lint:
    name: Lint with Flake8
    uses: giocaizzi/python-dev-actions/.github/workflows/linting.yml@main

  versioning:
    name: Versioning checks on PRs
    # it's coded only for pull requests
    if: github.event_name == 'pull_request'
    uses: giocaizzi/python-dev-actions/.github/workflows/versioning.yml@main
