name: Pre-checks

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version"
        type: string
        default: "3.9"
      os:
        description: "Operating system"
        type: string
        default: "ubuntu-latest"

jobs:
  pre-checks:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # required for the versioning action

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Lint with Flake8
        uses: giocaizzi/python-dev-actions/.github/actions/lint@main

      - name: Versioning checks
        # it's coded only for pull requests, this avoids if erroneously called on push
        if: github.event_name == 'pull_request'
        uses: giocaizzi/python-dev-actions/.github/actions/versioning@main

      - name: PR Documentation prechecks on ubuntu-latest
        if: github.event_name == 'pull_request' && inputs.os == 'ubuntu-latest'
        uses: giocaizzi/python-dev-actions/.github/actions/documentation-merge-check@main