name: Test a specific Python version

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        type: string
        required: true
        default: '3.9'
      os:
        description: 'Operating system'
        type: string
        default: 'ubuntu-latest'

jobs:
  tests:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .
        pip install -r tests/requirements.txt

    # pytest params specified in pytest.ini
    - run: |
        pytest 
      

