name: Run tests

on:
    workflow_call:
        inputs:
            python-versions:
              description: 'Stringfied list of Python versions'
              type: string
              # double quotes outside and single quotes inside
              # for json parsing
              default: "['3.7', '3.8', '3.9', '3.10']"
            os:
              description: 'Operating system'
              type: string
              default: 'ubuntu-latest'

jobs:
    tests:
        runs-on: ${{ inputs.os }}
        strategy:
        # allow the matrix to not fail completely if one fails
          fail-fast: false
          matrix:
            # os: [ubuntu-latest] #macos-latest
            python-version: ${{fromJson(inputs.python-versions)}}

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
                
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install .
                pip install -r tests/requirements.txt
        
            # pytest params specified in pytest.ini
            - run: |
                pytest 
            
            - name: "Upload coverage to Codecov"
              uses: codecov/codecov-action@v3
              if: matrix.python-version == '3.10'